[WIP] Added button to payout bounty
leapdao/MultiSigWallet pull request #9
Opened 2019-10-31 19:01 UTC by eswarasai

### Description
- [x] Added interface for the ease of paying out bounties

Fixes: #8 

### TODO:
- [ ] Handle different scenarios of paying out bounties i.e., `gardener`/`worker`/`reviewer`
- [ ] Create a multisig transaction with required input parameters to payout bounty

2019-11-01 12:48 UTC, eswarasai commented
@troggy - I think this is ready for initial review. Few of the things are missing from below:

- Add validation for `worker` and `reviewer` address
- Not sure if we need to add `isRepOnly` checkbox and also how it fits in exactly

Let me know your initial review/thoughts, so that I can quickly iterate. Thanks!

2019-11-01 13:22 UTC, troggy commented
thanks, I will review 👍

> Not sure if we need to add isRepOnly checkbox and also how it fits in exactly

Yes, it is needed. Sometimes we want just to register reputation, not actual payout. I can imagine that `Reputation only` checkbox should affect transaction like that:
- If "Reputation only" checkbox is unchecked, do nothing
- if "Reputation only" checkbox is checked then dapp should add 1 wei to the amount (no need to reflect amount change on the UI of course)

For instance:
200 DAI + "Reputation only" checked → 200 × 100000000000000000**1** is sent in transaction
200 DAI + "Reputation only" unchecked → 200 × 000000000000000000 is sent in transaction

2019-11-01 13:57 UTC, eswarasai commented
@troggy - Thanks for the detailed explanation. I'll incorporate the above change as well 👍 

One more thing to note is, I'm only using `payout()` method of the `BountyPayout` contract as the UI handles the default `gardener`, `worker` and `reviewer` fields. Moreover if the amount of `worker`/`reviewer` is 0, the actual payout isn't sent anyway. I hope this behaviour is fine. Thanks!

2019-11-01 15:16 UTC, troggy commented
@eswarasai I've fixed an error in my previous message:
In example with 200 reputation payout correct value is
```
200 × 1000000000000000000 + 1
```

2019-11-01 15:36 UTC, eswarasai commented
@troggy - No worries. I got the gist of what should be done. I've been going through the `leap-contracts` PR for Bounty Payout V2 as well for the reference to ensure I'm implementing things right 😅

2019-11-02 12:36 UTC, eswarasai commented
@troggy - Added the reputation only checkbox as well 🙂

2019-11-02 15:22 UTC, troggy commented on dapp/src/controllers/payoutBountyCtrl.js
> +          const _bountyId = toHex($scope.bountyId.replace('github.com/leapdao', ''));
```suggestion
          const _bountyId = toHex($scope.bountyId.replace('https://github.com/leapdao', ''));
```

2019-11-02 16:00 UTC, johannbarbie commented
filled out this payment:
<img width="592" alt="Screen Shot 2019-11-02 at 4 58 23 PM" src="https://user-images.githubusercontent.com/659301/68073597-1ae86080-fd92-11e9-9419-82fcc10dbe52.png">

*expected:*
function `payoutReviewedDelivery()` would be called.

*actual:*
function `payout()` was called:
<img width="1159" alt="Screen Shot 2019-11-02 at 4 58 44 PM" src="https://user-images.githubusercontent.com/659301/68073616-394e5c00-fd92-11e9-8b76-c8ba1a83f22a.png">

2019-11-02 16:02 UTC, johba37 requested changes
incorrect function called here?
https://github.com/leapdao/MultiSigWallet/pull/9#issuecomment-549056626

2019-11-02 16:07 UTC, troggy commented
@johannbarbie that was me who confused @eswarasai to use `payout()` for any payment (it is simpler). I wasn't aware of gas savings you get if you use `payoutReviewedDelivery()` back then

2019-11-02 16:08 UTC, eswarasai commented
@johannbarbie - For the ease of it, I'm just calling the `payout` method even when there's no worker/reviewer with their respective amounts `0` since the payment won't happen. In case you'd like to have better transaction history, I can do the necessary handling of calling the particular method in case of each scenario.

Just to be sure I don't misunderstand the use cases, please do list which function to be called in each scenario. Thanks 🙂

2019-11-02 16:08 UTC, johannbarbie commented
> @johannbarbie that was me who confused @eswarasai to use `payout()` for any payment (it is simpler). I wasn't aware of gas savings you get if you use `payoutReviewedDelivery()` back then

because of the colony overhead, it is quite a lot, x00,000 i think 🌻

2019-11-02 16:10 UTC, johannbarbie commented
gardener + worker + reviewer => `payout()`
gardener + reviewer =>  `payoutReviewedDelivery()`
gardener + worker => `payoutNoReviewer()`

2019-11-02 16:13 UTC, eswarasai commented
@johannbarbie - I see that you've already tested the code on `mainnet`? Apart from the above method change, is there anything else needed to be handled?

I'm wondering if we need the below or not? Let me know if it's of priority.
- Add validation for worker and reviewer address

cc: @troggy

2019-11-02 16:18 UTC, troggy commented
> Add validation for worker and reviewer address

it should be easy to add. Otherwise, not a priority — the tool is for internal use. IMO

2019-11-02 16:24 UTC, johannbarbie commented
> I see that you've already tested the code on mainnet? 

yeah, here: https://etherscan.io/tx/0x228b47e236caada562f9d7a31e57ccc98f972d360c741c2ae4716e1febafb100

> Apart from the above method change, is there anything else needed to be handled?

in the bountyURL field, there is no length check.
if people enter `https://github.com/leapdao/MultiSigWallet/issues/8`
then only `/MultiSigWallet/issues/8` should be converted to hex (everything after leapdao):
=> `0x2f4d756c746953696757616c6c65742f6973737565732f38`
you are doing that already correctly.

the bountyURL field is only 32 bytes in length, so if the part after `https://github.com/leapdao` is longer than 32 characters, user should see an error

2019-11-02 17:09 UTC, eswarasai commented
@johannbarbie - Thanks for the above comment. I'll add the 32 characters length check as well.

> payout() 1.5M
> payoutNoReviewer() 1.0M

Looking at these values, I'm afraid I need to increase the `gas` for the transaction options? Right now it's just `500,000`. Let me know what should be the `gas` limits for all the 3 methods. Thanks! 🙂

2019-11-02 17:11 UTC, johannbarbie commented
> Looking at these values, I'm afraid I need to increase the `gas` for the transaction options? Right now it's just `500,000`. Let me know what should be the `gas` limits for all the 3 methods. Thanks! 🙂

don't worry about that. the values i've listed are for executing transactions. initializing transactions is way cheaper.

2019-11-02 17:30 UTC, eswarasai commented
@johannbarbie - So based on the below scenarios, I'm assuming that there'll always be either `worker` or `reviewer` along with `gardener` for bounty payout?

> gardener + worker + reviewer => payout()
> gardener + reviewer => payoutReviewedDelivery()
> gardener + worker => payoutNoReviewer()

In case both `worker` & `reviewer` details are not present, would it be alright if I don't allow the Payout to happen? Thanks!

2019-11-02 17:41 UTC, eswarasai commented
@johannbarbie - Updated the PR with all the validations as well as calling respective methods in case of no worker/reviewer. Please do test and let me know if there's anything else pending.

Before merging, if you can let me know the deployed Mainnet address of the Bounty Payout V2 contract, I'll do a quick commit for that as well. Thanks!

cc: @troggy

2019-11-03 10:03 UTC, johannbarbie commented
> In case both `worker` & `reviewer` details are not present, would it be alright if I don't allow the Payout to happen? Thanks!

in LeapDAO payouts are only supposed to happen if 2 pairs of eyes were involved. hence either worker or reviewer has to be present :)

2019-11-03 10:06 UTC, johannbarbie commented
for max value i saw you used `999999999999999`, our biggest bounty is 1400 DAI, so we could use that.

2019-11-03 10:07 UTC, johba37 approved these changes
great work

2019-11-03 12:00 UTC, eswarasai commented
@johannbarbie - Thanks for the approval. I can update the max value for amount field to 1400 but I also see the below statement in the policy:

> If 2 people work on the bounty together, the payout increases by 1.5x.
Should I increase the max value to `1.5x 1400 = 2100` then?

2019-11-03 12:10 UTC, johannbarbie commented
> Should I increase the max value to `1.5x 1400 = 2100` then?

yes, great point 👍

2019-11-03 12:13 UTC, eswarasai commented
@johannbarbie - Updated. Let me know if there's anything else needed or good to be merged 🙂

2019-11-03 13:34 UTC, merged